# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='message_html',
            new_name='business_name_html',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('user', 'business_name')]),
        ),
    ]
