# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180527_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='description',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='description_html',
            new_name='location_html',
        ),
    ]
